import os
from SAT import SAT, NextSAT, Clause


def readFile(path: str):
    if not (os.path.isfile(path)):
        raise Exception("File does not exist in relative path: '" + path + '\'')

    satInstance = []
    for line in open(path, "r"):
        if isNotClauseLine(line):
            satInstance.append(getClauseFromLine(line))
    return satInstance


def getClauseFromLine(line: str):
    satClause = line.replace('\n', '').replace(' 0', '').split(' ')
    while "" in satClause:
        satClause.remove("")
    return satClause


def isNotClauseLine(line: str):
    return not line.startswith("c") and not line.startswith("p")


def parseFile(path):
    clauses = list(map(lambda str_clause: Clause(str_clause), readFile(path)))
    sat = SAT(clauses)
    return sat


def exportToDimacs(satObj: SAT):
    output = "c Generated by 2X-SAT - Univalle - 2020\n"
    output += "p cnf " + str(satObj.vars.__len__()) + " " + str(satObj.clauses.__len__()) + "\n"

    literals = []
    literalsToConvert = []
    literalsConverted = []
    maxLiteralValue = None

    for clause in satObj.clauses:
        for literal in clause.literals:
            try:
                intValue = int(literal.name)
                literals.append(intValue) if intValue not in literals else literals
                maxLiteralValue = intValue if not maxLiteralValue else max(maxLiteralValue, intValue)
            except ValueError:
                literalsToConvert.append(literal.name) if literal.name not in literalsToConvert else literalsToConvert

    for i in literalsToConvert:
        maxLiteralValue += 1
        nextIntLiteral = maxLiteralValue
        literalsConverted.append(nextIntLiteral)

    # print(maxLiteralValue)
    # print(literals)
    # print(literalsToConvert)
    # print(literalsConverted)

    return output
